language: python
python:
  - '2.7'
install:
  - 'travis_wait pip install -r requirements.txt --use-mirrors'
  - 'pip install coveralls'
script:
  - 'py.test --doctest-modules --ignore setup.py --cov dabbiew.dabbiew'
after_success:
  - 'coveralls'
