language: python
python:
  - '2.7'
before-install:
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - py.test --doctest-modules --ignore setup.py --cov dabbiew
after_success:
  - coveralls
